CATEGORIES = {
    "Animals": [
        {"word": "Lion", "hint": "Predator"},
        {"word": "Elephant", "hint": "Herbivore"},
        {"word": "Penguin", "hint": "Bird"},
        {"word": "Dolphin", "hint": "Mammal"},
        {"word": "Eagle", "hint": "Hunter"},
        {"word": "Tiger", "hint": "Carnivore"},
        {"word": "Bear", "hint": "Omnivore"},
        {"word": "Kangaroo", "hint": "Marsupial"},
        {"word": "Giraffe", "hint": "Herbivore"},
        {"word": "Octopus", "hint": "Invertebrate"},
        {"word": "Whale", "hint": "Mammal"},
        {"word": "Butterfly", "hint": "Insect"},
        {"word": "Snake", "hint": "Reptile"},
        {"word": "Wolf", "hint": "Pack"},
        {"word": "Peacock", "hint": "Bird"},
    ],
    "Food": [
        {"word": "Pizza", "hint": "Fast"},
        {"word": "Sushi", "hint": "Dish"},
        {"word": "Pasta", "hint": "Carb"},
        {"word": "Burger", "hint": "Meal"},
        {"word": "Taco", "hint": "Street"},
        {"word": "Salad", "hint": "Healthy"},
        {"word": "Cake", "hint": "Dessert"},
        {"word": "Ice Cream", "hint": "Dessert"},
        {"word": "Coffee", "hint": "Drink"},
        {"word": "Apple", "hint": "Fruit"},
        {"word": "Chocolate", "hint": "Sweet"},
        {"word": "Cheese", "hint": "Dairy"},
        {"word": "Bread", "hint": "Staple"},
        {"word": "Spaghetti", "hint": "Pasta"},
        {"word": "Donut", "hint": "Dessert"},
    ],
    "Sports": [
        {"word": "Soccer", "hint": "Team"},
        {"word": "Basketball", "hint": "Court"},
        {"word": "Tennis", "hint": "Racket"},
        {"word": "Golf", "hint": "Club"},
        {"word": "Swimming", "hint": "Water"},
        {"word": "Boxing", "hint": "Combat"},
        {"word": "Cricket", "hint": "Bat"},
        {"word": "Baseball", "hint": "Field"},
        {"word": "Volleyball", "hint": "Net"},
        {"word": "Badminton", "hint": "Racket"},
        {"word": "Skiing", "hint": "Winter"},
        {"word": "Surfing", "hint": "Water"},
        {"word": "Skateboarding", "hint": "Board"},
        {"word": "Cycling", "hint": "Endurance"},
        {"word": "Gymnastics", "hint": "Routine"},
    ],
    "Movies": [
        {"word": "Avatar", "hint": "SciFi"},
        {"word": "Inception", "hint": "Thriller"},
        {"word": "Titanic", "hint": "Drama"},
        {"word": "Jaws", "hint": "Horror"},
        {"word": "Forrest Gump", "hint": "Drama"},
        {"word": "The Matrix", "hint": "Action"},
        {"word": "Interstellar", "hint": "SciFi"},
        {"word": "Gladiator", "hint": "Historical"},
        {"word": "Jurassic Park", "hint": "Adventure"},
        {"word": "Toy Story", "hint": "Animated"},
        {"word": "The Dark Knight", "hint": "Action"},
        {"word": "Pulp Fiction", "hint": "Crime"},
        {"word": "Parasite", "hint": "Drama"},
        {"word": "Casablanca", "hint": "Romance"},
        {"word": "Frozen", "hint": "Animated"},
    ],
    "Countries": [
        {"word": "Japan", "hint": "Island"},
        {"word": "Brazil", "hint": "Tropical"},
        {"word": "Egypt", "hint": "Desert"},
        {"word": "Canada", "hint": "Northern"},
        {"word": "Australia", "hint": "Island"},
        {"word": "India", "hint": "Populous"},
        {"word": "France", "hint": "European"},
        {"word": "Germany", "hint": "European"},
        {"word": "Mexico", "hint": "Latin"},
        {"word": "Italy", "hint": "European"},
        {"word": "Spain", "hint": "European"},
        {"word": "Greece", "hint": "Mediterranean"},
        {"word": "Sweden", "hint": "Nordic"},
        {"word": "Netherlands", "hint": "European"},
        {"word": "Portugal", "hint": "Coastal"},
    ],
    "Professions": [
        {"word": "Doctor", "hint": "Medical"},
        {"word": "Teacher", "hint": "Education"},
        {"word": "Lawyer", "hint": "Legal"},
        {"word": "Engineer", "hint": "Technical"},
        {"word": "Chef", "hint": "Culinary"},
        {"word": "Musician", "hint": "Creative"},
        {"word": "Actor", "hint": "Performance"},
        {"word": "Astronaut", "hint": "Space"},
        {"word": "Pilot", "hint": "Aviation"},
        {"word": "Firefighter", "hint": "Emergency"},
        {"word": "Detective", "hint": "Investigation"},
        {"word": "Nurse", "hint": "Medical"},
        {"word": "Farmer", "hint": "Agriculture"},
        {"word": "Architect", "hint": "Design"},
        {"word": "Journalist", "hint": "Media"},
    ],
    "Seasons & Weather": [
        {"word": "Summer", "hint": "Season"},
        {"word": "Winter", "hint": "Season"},
        {"word": "Spring", "hint": "Season"},
        {"word": "Fall", "hint": "Season"},
        {"word": "Rain", "hint": "Precipitation"},
        {"word": "Sunshine", "hint": "Weather"},
        {"word": "Snow", "hint": "Precipitation"},
        {"word": "Thunder", "hint": "Storm"},
        {"word": "Tornado", "hint": "Storm"},
        {"word": "Hurricane", "hint": "Storm"},
        {"word": "Frost", "hint": "Cold"},
        {"word": "Hail", "hint": "Precipitation"},
        {"word": "Breeze", "hint": "Wind"},
        {"word": "Storm", "hint": "Weather"},
        {"word": "Blizzard", "hint": "Storm"},
    ],
    "Technology": [
        {"word": "Computer", "hint": "Device"},
        {"word": "Phone", "hint": "Device"},
        {"word": "Robot", "hint": "Machine"},
        {"word": "Drone", "hint": "Machine"},
        {"word": "Satellite", "hint": "Space"},
        {"word": "Laptop", "hint": "Device"},
        {"word": "Tablet", "hint": "Device"},
        {"word": "Keyboard", "hint": "Input"},
        {"word": "Mouse", "hint": "Input"},
        {"word": "Printer", "hint": "Output"},
        {"word": "Camera", "hint": "Device"},
        {"word": "Television", "hint": "Media"},
        {"word": "Speaker", "hint": "Audio"},
        {"word": "Microchip", "hint": "Component"},
        {"word": "Internet", "hint": "Network"},
    ],
    "Colors": [
        {"word": "Red", "hint": "Primary"},
        {"word": "Blue", "hint": "Primary"},
        {"word": "Green", "hint": "Color"},
        {"word": "Yellow", "hint": "Primary"},
        {"word": "Purple", "hint": "Color"},
        {"word": "Orange", "hint": "Color"},
        {"word": "Pink", "hint": "Color"},
        {"word": "Brown", "hint": "Color"},
        {"word": "Gray", "hint": "Neutral"},
        {"word": "Black", "hint": "Neutral"},
        {"word": "White", "hint": "Neutral"},
        {"word": "Cyan", "hint": "Color"},
        {"word": "Magenta", "hint": "Color"},
        {"word": "Turquoise", "hint": "Color"},
        {"word": "Gold", "hint": "Metal"},
    ],
    "Emotions": [
        {"word": "Happy", "hint": "Positive"},
        {"word": "Sad", "hint": "Negative"},
        {"word": "Angry", "hint": "Negative"},
        {"word": "Excited", "hint": "Arousal"},
        {"word": "Nervous", "hint": "Arousal"},
        {"word": "Confused", "hint": "Cognitive"},
        {"word": "Surprised", "hint": "Reaction"},
        {"word": "Frustrated", "hint": "Negative"},
        {"word": "Calm", "hint": "Low"},
        {"word": "Anxious", "hint": "Arousal"},
        {"word": "Proud", "hint": "Positive"},
        {"word": "Embarrassed", "hint": "Social"},
        {"word": "Jealous", "hint": "Social"},
        {"word": "Hopeful", "hint": "Positive"},
        {"word": "Worried", "hint": "Negative"},
    ],
}